services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - APP_MODULE=app.main:app
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - ALLOW_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - sqlite_data:/app/db # Persist SQLite database
    restart: unless-stopped
    command: uvicorn --reload --host 0.0.0.0 --port 8000 app.main:app

volumes:
  sqlite_data:
